export default function robots() {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || "https://www.lucirajewelry.com";

  return {
    rules: [
      // --- ✅ Explicitly Allow OpenAI Bots ---
      {
        userAgent: ["GPTBot", "OAI-SearchBot", "ChatGPT-User"],
        disallow: "",
      },
      // --- ✅ Explicit Googlebot Instructions ---
      {
        userAgent: "Googlebot",
        disallow: "",
      },
      // --- ✅ Disallow Amazon Bot Completely ---
      {
        userAgent: "AmazonProductDiscoverybot",
        disallow: "/",
      },
      // --- ✅ Shopify Default Bot Rules & Catch-all ---
      {
        userAgent: "*",
        disallow: [
          "/a/downloads/-/*",
          "/admin",
          "/cart",
          "/orders",
          "/checkouts/",
          "/checkout",
          "/73985163482/checkouts",
          "/73985163482/orders",
          "/carts",
          "/account",
          "/collections/*sort_by*",
          "/*/collections/*sort_by*",
          "/collections/*+*",
          "/collections/*%2B*",
          "/collections/*%2b*",
          "/*/collections/*+*",
          "/*/collections/*%2B*",
          "/*/collections/*%2b*",
          "*/collections/*filter*&*filter*",
          "/blogs/*+*",
          "/blogs/*%2B*",
          "/blogs/*%2b*",
          "/*/blogs/*+*",
          "/*/blogs/*%2B*",
          "/*/blogs/*%2b*",
          "/*?*oseid=*",
          "/*preview_theme_id*",
          "/*preview_script_id*",
          "/policies/",
          "/*/policies/",
          "/*/*?*ls=*&ls=*",
          "/*/*?*ls%3D*%3Fls%3D*",
          "/*/*?*ls%3d*%3fls%3d*",
          "/search",
          "/apple-app-site-association",
          "/.well-known/shopify/monorail",
          "/cdn/wpm/*.js",
          "/recommendations/products",
          "/*/recommendations/products",
          "/services/login_with_shop",
          "/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
        ],
      },
      // --- ✅ adsbot-google rules ---
      {
        userAgent: "adsbot-google",
        disallow: [
          "/checkouts/",
          "/checkout",
          "/carts",
          "/orders",
          "/73985163482/checkouts",
          "/73985163482/orders",
          "/*?*oseid=*",
          "/*preview_theme_id*",
          "/*preview_script_id*",
          "/cdn/wpm/*.js",
          "/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/services/login_with_shop",
        ],
      },
      // --- ✅ Nutch ---
      {
        userAgent: "Nutch",
        disallow: "/",
      },
      // --- ✅ AhrefsBot & AhrefsSiteAudit ---
      {
        userAgent: ["AhrefsBot", "AhrefsSiteAudit"],
        disallow: [
          "/a/downloads/-/*",
          "/admin",
          "/cart",
          "/orders",
          "/checkouts/",
          "/checkout",
          "/73985163482/checkouts",
          "/73985163482/orders",
          "/carts",
          "/account",
          "/collections/*sort_by*",
          "/*/collections/*sort_by*",
          "/collections/*+*",
          "/collections/*%2B*",
          "/collections/*%2b*",
          "/*/collections/*+*",
          "/*/collections/*%2B*",
          "/*/collections/*%2b*",
          "*/collections/*filter*&*filter*",
          "/blogs/*+*",
          "/blogs/*%2B*",
          "/blogs/*%2b*",
          "/*/blogs/*+*",
          "/*/blogs/*%2B*",
          "/*/blogs/*%2b*",
          "/*?*oseid=*",
          "/*preview_theme_id*",
          "/*preview_script_id*",
          "/policies/",
          "/*/policies/",
          "/*/*?*ls=*&ls=*",
          "/*/*?*ls%3D*%3Fls%3D*",
          "/*/*?*ls%3d*%3fls%3d*",
          "/search",
          "/apple-app-site-association",
          "/.well-known/shopify/monorail",
          "/cdn/wpm/*.js",
          "/services/login_with_shop",
          "/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
          "/*/collections/*/products/*-[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]-remote",
        ],
        crawlDelay: 10,
      },
      // --- ✅ MJ12bot ---
      {
        userAgent: "MJ12bot",
        crawlDelay: 10,
      },
      // --- ✅ Pinterest ---
      {
        userAgent: "Pinterest",
        crawlDelay: 1,
      },
      // --- ✅ Crawl-delay for all other bots ---
      {
        userAgent: "*",
        crawlDelay: 10,
      },
      // --- 🚫 Disallow Pagination URLs ---
      {
        userAgent: "*",
        disallow: ["/*?page=", "/*?*section_id="],
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
      "https://luciraonline.myshopify.com/sitemap.xml",
    ],
  };
}
